# Generated by Django 4.0.4 on 2022-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('download_link', models.CharField(max_length=2083)),
                ('description', models.CharField(max_length=2100)),
            ],
        ),
    ]
